apiVersion: v1
kind: Command
metadata:
  name: 碧蓝航线
  label:
    en_US: blhx
    zh_Hans: 碧蓝航线
  description:
    en_US: 'Look up the wiki content for each game'
    zh_Hans: '查询各个游戏的维基内容'
spec:
execution:
  python:
    path: get.py
    attr: Get