# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from typing import Any, AsyncGenerator
import os

from langbot_plugin.api.definition.components.command.command import Command, Subcommand
from langbot_plugin.api.entities.builtin.command.context import ExecuteContext, CommandReturn


class Help(Command):

    async def initialize(self):
        await super().initialize()

        "Fill with your code here"

        @self.subcommand(
            name="",  # 空字符串表示根命令
            help="Show information of the query",  # 命令帮助信息
            usage="!help",  # 命令使用示例，显示在命令帮助信息中
            aliases=["h"],  # 命令别名
        )
        async def send(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            print(context)

            reply_text = (f"这是一个帮助功能\n"
                          f"目前支持的wiki有碧蓝航线\n"
                          f"输入 !help 碧蓝航线 可查看相关帮助命令\n"
                          f"其他分区同理\n"
                          f"================================\n"
                          f"これはヘルプ機能です\n"
                          f"現在対応しているWikiは「アズールレーン」です\n"
                          f"「!help アズールレーン」と入力すると、関連するヘルプコマンドを確認できます\n"
                          f"他のカテゴリも同様です\n"
                          f"================================\n"
                          f"This is a help feature\n"
                          f"Currently supported wiki: Azur Lane\n"
                          f"Enter !help AzurLane to view related help commands\n"
                          f"Other sections work the same way")


            yield CommandReturn(
                text=reply_text,
            )

        @self.subcommand(
            name="碧蓝航线",  # 空字符串表示根命令
            help="Show information of the query",  # 命令帮助信息
            usage="!help 碧蓝航线",  # 命令使用示例，显示在命令帮助信息中
            aliases=["碧蓝航线"],  # 命令别名
        )
        async def send(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            print(context)
            target_title = "## 碧蓝航线"
            capture = False
            section_lines = []
            try:
                with open('./readme/README_zh_Hans.md', 'r', encoding="utf-8") as f:
                    for line in f:
                        if line.strip() == target_title:
                            capture = True
                            continue
                        # 遇到下一个同级或更高级标题就停止
                        if line.startswith("##") and capture:
                            break
                        if capture:
                            section_lines.append(line.strip())

                reply_text = '\n'.join(section_lines)

                yield CommandReturn(
                    text=reply_text,
                )
            except Exception as e:
                yield CommandReturn(
                    text=f'命令导入失败，错误信息：{e}',
                )

        @self.subcommand(
            name="アズールレーン",  # 空字符串表示根命令
            help="Show information of the query",  # 命令帮助信息
            usage="!help アズールレーン",  # 命令使用示例，显示在命令帮助信息中
            aliases=["アズールレーン"],  # 命令别名
        )
        async def send(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            print(context)
            target_title = "## アズールレーン"
            capture = False
            section_lines = []
            try:
                with open('./readme/README_ja_JP.md', 'r', encoding="utf-8") as f:
                    for line in f:
                        if line.strip() == target_title:
                            capture = True
                            continue
                        # 遇到下一个同级或更高级标题就停止
                        if line.startswith("##") and capture:
                            break
                        if capture:
                            section_lines.append(line.strip())

                reply_text = '\n'.join(section_lines)

                yield CommandReturn(
                    text=reply_text,
                )
            except Exception as e:
                yield CommandReturn(
                    text=f'命令导入失败，错误信息：{e}',
                )

        @self.subcommand(
            name="AzurLane",  # 空字符串表示根命令
            help="Show information of the query",  # 命令帮助信息
            usage="!help AzurLane",  # 命令使用示例，显示在命令帮助信息中
            aliases=["AzurLane"],  # 命令别名
        )
        async def send(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            print(context)
            target_title = "## Azur Lane"
            capture = False
            section_lines = []
            try:
                with open('./README.md', 'r', encoding="utf-8") as f:
                    for line in f:
                        if line.strip() == target_title:
                            capture = True
                            continue
                        # 遇到下一个同级或更高级标题就停止
                        if line.startswith("##") and capture:
                            break
                        if capture:
                            section_lines.append(line.strip())

                reply_text = '\n'.join(section_lines)

                yield CommandReturn(
                    text=reply_text,
                )
            except Exception as e:
                yield CommandReturn(
                    text=f'命令导入失败，错误信息：{e}',
                )

        # async def send(self, event_context: context.EventContext):
        #     reply_text = f"这是一个帮助功能"
        #     img_path = "C:/Users/Lenovo/Pictures/几把兔.jpg"
        #     with open(img_path, "rb") as f:
        #         img_bytes = f.read()
        #         img_base64 = base64.b64encode(img_bytes).decode("utf-8")
        #
        #     try:
        #         # 发送图片
        #         await event_context.reply(
        #             platform_message.MessageChain([
        #                 platform_message.Plain(text=f"这是一个帮助功能"),
        #                 platform_message.Image(base64=img_base64)
        #             ])
        #         )
        #
        #     except Exception as e:
        #         await event_context.reply(
        #             platform_message.MessageChain([
        #                 platform_message.Plain(text=f"发生错误: {str(e)}")
        #             ])
        #         )
        #
        #     event_context.prevent_default()  # 直接返回到聊天平台
        #
        #     if False:   # 占位，勿删
        #         yield





