# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import base64

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message
from langbot_plugin.api.entities.builtin.provider import message as provider_message


class DefaultEventListener(EventListener):

    def __init__(self):
        super().__init__()
        
        @self.handler(events.PersonNormalMessageReceived)
        async def handler(event_context: context.EventContext):
            print("Hello LangBot Plugin!")
            print(event_context)

            event_context.prevent_default()

            # event_context.event.reply_message_chain = platform_message.MessageChain([
            #     platform_message.Plain(text=f"Hello from LangBot Plugin!"),
            # ])
            
            # Simple text response
            # await event_context.reply(
            #     platform_message.MessageChain([
            #         platform_message.Plain(text=f"Hello from LangBot Plugin! 1"),
            #     ])
            # )

            with open("assets/image.png", "rb") as f:
                image_data = f.read()
                image_base64 = base64.b64encode(image_data).decode("utf-8")
                image = platform_message.Image(base64=f"data:image/png;base64,{image_base64}")

            # Comprehensive test message with various components
            await event_context.reply(
                platform_message.MessageChain([
                    platform_message.Plain(text="This is a test message, containing various component types:\n"),
                    platform_message.Plain(text="1. Text message "),
                    platform_message.At(target=event_context.event.sender_id, display="@you"),
                    platform_message.Plain(text="\n2. At someone\n"),
                    platform_message.Plain(text="3. Image (example)\n"),
                    image,
                    platform_message.Plain(text="\n4. Voice (example)\n"),
                    platform_message.Voice(
                        url="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                        length=60
                    ),
                    platform_message.Plain(text="\n5. File (example)\n"),
                    platform_message.File(
                        name="test_document.pdf",
                        size=1024000,
                        url="https://example.com/test.pdf"
                    ),
                    platform_message.Plain(text="\n✅ All components tested successfully!"),
                ])
            )

            # Test message with Quote component
            await event_context.reply(
                platform_message.MessageChain([
                    platform_message.Quote(
                        id=event_context.event.message_chain.message_id,
                        sender_id=event_context.event.sender_id,
                        origin=[platform_message.Plain(text="Quote the original message")]
                    ),
                    platform_message.Plain(text="This is a quoted reply message"),
                ])
            )
