# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import base64
from typing import Any, AsyncGenerator

from langbot_plugin.entities.io.errors import ActionCallError
from playwright.async_api import async_playwright

from langbot_plugin.api.definition.components.command.command import Command, Subcommand
from langbot_plugin.api.entities.builtin.command.context import ExecuteContext, CommandReturn



class Get(Command):
    
    async def initialize(self):
        await super().initialize()
        
        "Fill with your code here"

        @self.subcommand(
            name="",  # 空字符串表示根命令
            help="Show information of the query",  # 命令帮助信息
            usage="!碧蓝航线",  # 命令使用示例，显示在命令帮助信息中
            aliases=["blhx"],  # 命令别名
        )
        async def send(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            reply_text = (f"欢迎使用维基百科查询功能，目前支持“ 碧蓝航线wiki ”。\n"
                          f"以碧蓝航线为例，查询命令为“ !碧蓝航线 舰娘 拉菲II ” 中间要通过空格分隔开。\n"
                          f"详情命令可通过“ !help ”进行查询")

            yield CommandReturn(
                text=reply_text
            )

        @self.subcommand(
            name="舰娘",  # 空字符串表示根命令
            help="Show information of the query",  # 命令帮助信息
            usage="!碧蓝航线 舰娘",  # 命令使用示例，显示在命令帮助信息中
            aliases=["sg"],  # 命令别名

        )
        async def send(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            if context.crt_params:
                async with async_playwright() as p:
                    browser = await p.chromium.launch()
                    page = await browser.new_page()
                    await page.goto(f"https://wiki.biligame.com/blhx/{context.crt_params[0]}")

                    div = page.locator("#bodyContent")
                    await div.scroll_into_view_if_needed()
                    img_bytes = await div.screenshot(path="./static_data/blhx.png")
                    img_base64 = base64.b64encode(img_bytes).decode("ascii")
                    data_url = f"data:image/png;base64,{img_base64}"

                    await browser.close()

                reply_text = f"以下为“{context.crt_params[0]}”的信息及配装推荐"
                yield CommandReturn(
                    text=reply_text,
                    image_url=data_url,
                )
            else:
                reply_text = (f"欢迎使用 碧蓝航线wiki 查询功能。\n"
                              f"以查询舰娘为例，查询命令为\n"
                              f"=============================\n\n"
                              f"!碧蓝航线 舰娘 拉菲II\n\n"
                              f"=============================\n"
                              f"中间要通过空格分隔开。\n"
                              f"舰娘可以换成 装备 等其他类别\n"
                              f"详情命令可通过“ !help ”进行查询")

                yield CommandReturn(
                    text=reply_text
                )

        @self.subcommand(
            name="装备",  # 空字符串表示根命令
            help="Show information of the query",  # 命令帮助信息
            usage="!碧蓝航线 装备",  # 命令使用示例，显示在命令帮助信息中
            aliases=["zb"],  # 命令别名
        )
        async def send(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            try:
                if len(context.crt_params) == 1:
                    async with async_playwright() as p:
                        browser = await p.chromium.launch()
                        page = await browser.new_page()
                        await page.goto(f"https://wiki.biligame.com/blhx/{context.crt_params[0]}")

                        div = page.locator("#bodyContent")
                        await div.scroll_into_view_if_needed()
                        img_bytes = await div.screenshot(path="./static_data/blhx.png")
                        img_base64 = base64.b64encode(img_bytes).decode("ascii")
                        data_url = f"data:image/png;base64,{img_base64}"

                        await browser.close()
                    reply_text = f"以下为“{context.crt_params[0]}”的信息及获取方式"
                    yield CommandReturn(
                        text=reply_text,
                        image_url=data_url,
                    )
                elif len(context.crt_params) == 2:
                    row = context.crt_params[0]
                    col = context.crt_params[1]
                    try:
                        async with async_playwright() as p:
                            localization = (int(row) - 1) * 16 + int(col)
                            browser = await p.chromium.launch()
                            page = await browser.new_page()
                            await page.goto(f"https://wiki.biligame.com/blhx/装备图鉴")
                            name_url = page.locator(f"#CardSelectTr > div:nth-child({localization}) > span > a")
                            name = await name_url.text_content()
                            if not name:
                                yield CommandReturn(
                                    text='坐标传入数值有误，请重新计算坐标',
                                )
                                return
                            await page.goto(f"https://wiki.biligame.com/blhx/{name}")

                            div = page.locator("#bodyContent")
                            await div.scroll_into_view_if_needed()
                            img_bytes = await div.screenshot(path="./static_data/blhx.png")
                            img_base64 = base64.b64encode(img_bytes).decode("ascii")
                            data_url = f"data:image/png;base64,{img_base64}"

                            await browser.close()
                        reply_text = f"以下为“{name}”的信息及获取方式"
                        yield CommandReturn(
                            text=reply_text,
                            image_url=data_url,
                        )

                    except ValueError:
                        yield CommandReturn(
                            text="坐标传入格式有误，请参考下方示例\n"
                                 "=============================\n\n"
                                 "!碧蓝航线 装备 1 1\n\n"
                                 "=============================\n",
                        )

                else:
                    async with async_playwright() as p:
                        browser = await p.chromium.launch()
                        page = await browser.new_page()
                        await page.goto(f"https://wiki.biligame.com/blhx/装备图鉴")

                        div = page.locator("#bodyContent")
                        await div.scroll_into_view_if_needed()
                        img_bytes = await div.screenshot(path="./static_data/blhx.png")
                        img_base64 = base64.b64encode(img_bytes).decode("ascii")
                        data_url = f"data:image/png;base64,{img_base64}"

                        await browser.close()
                    reply_text = (f"以下为主要装备列表\n"
                                  f"装备按坐标划分\n"
                                  f"如果想要通过图例坐标查询请参考以下示例\n"
                                  f"=============================\n\n"
                                  f"!碧蓝航线 装备 1 1\n\n"
                                  f"=============================\n"
                                  f"如果想要通过装备名称查询请参考以下示例（全名）\n"
                                  f"=============================\n\n"
                                  f"!碧蓝航线 装备 双联100mm98式高射炮改#T0\n\n"
                                  f"=============================\n"
                                  f"详情命令可通过“ !help ”进行查询")
                    yield CommandReturn(
                        text=reply_text,
                        image_url=data_url,
                    )
            except ActionCallError as e:
                if "TimeOut" in str(e):
                    yield CommandReturn(
                        text="网络超时，请检查网络设置，或者代理是否关闭",
                    )
                else:
                    yield CommandReturn(
                        text=f"其他错误{e}",
                    )

        @self.subcommand(
            name="月度",  # 空字符串表示根命令
            help="Show information of the query",  # 命令帮助信息
            usage="!碧蓝航线 月度",  # 命令使用示例，显示在命令帮助信息中
            aliases=["yd"],  # 命令别名
        )
        async def send(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            async with async_playwright() as p:
                browser = await p.chromium.launch()
                page = await browser.new_page()
                await page.goto(f"https://wiki.biligame.com/blhx/大型作战月度BOSS解析", wait_until='networkidle')

                div = page.locator("#bodyContent")
                await div.scroll_into_view_if_needed()
                img_bytes = await div.screenshot(path="./static_data/blhx.png")
                img_base64 = base64.b64encode(img_bytes).decode("ascii")
                data_url = f"data:image/png;base64,{img_base64}"

                await browser.close()

            reply_text = f"以下为“大型作战月度BOSS解析”的信息及阵容推荐"
            yield CommandReturn(
                text=reply_text,
                image_url=data_url,
            )

        @self.subcommand(
            name="井号",  # 空字符串表示根命令
            help="Show information of the query",  # 命令帮助信息
            usage="!碧蓝航线 井号",  # 命令使用示例，显示在命令帮助信息中
            aliases=["jh"],  # 命令别名
        )
        async def send(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            try:
                if context.crt_params[0] == "主线":
                    data_url = 'https://patchwiki.biligame.com/images/blhx/b/b5/bznssgm2jdkb6hn1wszgbtrizq757rt.jpg'

                elif context.crt_params[0] == "大世界":
                    data_url = 'https://patchwiki.biligame.com/images/blhx/a/aa/ten1zpz1y9zqwvc6pt7slzoo8p8lwwe.jpg'

                elif context.crt_params[0] == "装备":
                    data_url = 'https://patchwiki.biligame.com/images/blhx/a/ae/as8z68mrgz0048ydla0nc5fyb9b56td.jpg'

                elif context.crt_params[0] == "金部件":
                    data_url = 'https://patchwiki.biligame.com/images/blhx/0/06/jdyfaf5cjs7uw6gv1c3fjoqv895rhhr.jpg'

                elif context.crt_params[0] == "研发":
                    data_url = 'https://patchwiki.biligame.com/images/blhx/0/04/lkim27o7yz6zggg22q56fee2hyhts0f.png'

                else:
                    yield CommandReturn(
                        text='无法查询到数据\n'
                             '目前只支持 主线 大世界 装备 金部件 研发榜单查询\n'
                             '详情命令可通过“ !help ”进行查询',
                    )
                    return

                reply_text = f'以下为“{context.crt_params[0]}”养成推荐'
                yield CommandReturn(
                    text=reply_text,
                    image_url=data_url,
                )
                return
            except IndexError:
                yield CommandReturn(
                    text='请增加查询后缀词\n'
                         '目前只支持 主线 大世界 装备 金部件 研发榜单查询\n'
                         '详情命令可通过“ !help ”进行查询',
                )

