apiVersion: v1
kind: Command
metadata:
  name: help
  label:
    en_US: Help
    zh_Hans: Help
  description:
    en_US: 'Displays which commands can be used and what the command specifications are'
    zh_Hans: '显示可以使用哪些命令，以及命令规范有哪些'
spec:
execution:
  python:
    path: help.py
    attr: Help