# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import requests

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message


class DefaultEventListener(EventListener):

    async def initialize(self):
        await super().initialize()
        
        "Fill with your code here"

        @self.handler(events.GroupMessageReceived)
        @self.handler(events.PersonMessageReceived)
        async def handler(event_context: context.EventContext):
            message_chain = event_context.event.message_chain
            message = "".join(
                element.text for element in message_chain
                if isinstance(element, platform_message.Plain)
            ).strip()

            if '事件监听器' not in message:
                return
            print("Hello LangBot Plugin!")
            print(event_context)
            if event_context.event.sender_id == 1973367580:  # 请不要骚扰我，咕咕嘎嘎
                await event_context.reply(
                    platform_message.MessageChain([
                        platform_message.Plain(
                            text=f"这是您设计的一个事件监听器! Aizbend大人~"),
                    ])
                )
            else:
                data = {
                    "user_id": f"{event_context.event.sender_id}"  # 如果设置了token就要添加Authorization，没有token可以省略
                }
                resp = requests.post('http://127.0.0.1:3000/get_stranger_info', json=data)  # 域名和端口需自己更改，默认情况下不需要更改

                qq_user_name = resp.json().get('data').get('nick')

                await event_context.reply(
                    platform_message.MessageChain([
                        platform_message.Plain(text=f"这是一个事件监听器! {qq_user_name} 指挥官"),
                    ])
                )

            event_context.prevent_default()


